ALTER TABLE pacientes 
ADD COLUMN nivel_dolor TINYINT DEFAULT 0 COMMENT '0-10 escala de dolor',
ADD COLUMN comorbilidades JSON DEFAULT NULL COMMENT 'Array: CARDIACA, HIPERTENSION, DIABETES, OBESIDAD',
ADD COLUMN nivel_actividad_fisica VARCHAR(30) DEFAULT 'SEDENTARIO' COMMENT 'SEDENTARIO, MODERADAMENTE_ACTIVO, ACTIVO, DEPORTISTA';
